obj-y += flags_mx7.o
obj-y += fwupdate.o
obj-y += partitions.o
obj-$(CONFIG_CMD_KOBS) += cmd_kobs.o
obj-y += fsl_bch.o
obj-y += device_interface.o
obj-y += carrier_sue_demo_client.o
obj-y += carrier_generic_board.o
